services:
  gf-locator:
    image: apachegeode/geode:latest
    container_name: gf-locator
    hostname: gf-locator
    command: >
      gfsh start locator
      --name=locator
      --bind-address=0.0.0.0
      --port=10334
      --http-service-port=7070
      --enable-cluster-configuration=true
      --J=-Dgemfire.locators=gf-locator[10334]
    ports:
      - "10334:10334"  # Locator port
      - "7070:7070"    # Pulse UI
    networks:
      - geode-net

  gf-server1:
    image: apachegeode/geode:latest
    container_name: gf-server1
    hostname: gf-server1
    depends_on:
      - gf-locator
    command: >
      gfsh start server
      --name=server1
      --bind-address=0.0.0.0
      --server-port=40404
      --locators=gf-locator[10334]
      --J=-Xms512m --J=-Xmx512m
    ports:
      - "40404:40404"
    networks:
      - geode-net

  gf-server2:
    image: apachegeode/geode:latest
    container_name: gf-server2
    hostname: gf-server2
    depends_on:
      - gf-locator
    command: >
      gfsh start server
      --name=server2
      --bind-address=0.0.0.0
      --server-port=40405
      --locators=gf-locator[10334]
      --J=-Xms512m --J=-Xmx512m
    ports:
      - "40405:40405"
    networks:
      - geode-net

  gf-server3:
    image: apachegeode/geode:latest
    container_name: gf-server3
    hostname: gf-server3
    depends_on:
      - gf-locator
    command: >
      gfsh start server
      --name=server3
      --bind-address=0.0.0.0
      --server-port=40406
      --locators=gf-locator[10334]
      --J=-Xms512m --J=-Xmx512m
    ports:
      - "40406:40406"
    networks:
      - geode-net

  gf-client:
    image: apachegeode/geode:latest
    container_name: gf-client
    hostname: gf-client
    depends_on:
      - gf-locator
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    networks:
      - geode-net

networks:
  geode-net:
    driver: bridge
