ssl-keystore=/root/certs/keystore.p12
ssl-keystore-password=password
ssl-keystore-type=pkcs12
ssl-truststore=/root/certs/truststore.p12
ssl-truststore-password=password
ssl-truststore-type=pkcs12
ssl-ciphers=any
ssl-protocols=any
ssl-enabled-components=all
