services:
  gemfire-management-console:
    image: registry.packages.broadcom.com/gemfire-management-console/gemfire-management-console:1.3.0
    container_name: gemfire-management-console
    ports:
      - "8080:8080"
    restart: unless-stopped
