spring:
  application:
    name: my-gemfire-spring-client

gemfire:
  # GemFire Locator Configuration
  locator:
    host: gemfire1-locator-0.gemfire1-locator.default.svc.cluster.local
    port: 10334

  # GemFire SNI Proxy Configuration
  sni:
    host: localhost
    port: 9000

  # GemFire SSL Configuration
  ssl:
    certs-dir: ./certs
    storepass: unreDY6sNR08-IHBQcw0BADP_leu888D-R-12Lhh1LY=
    keystore-file: keystore.p12
    truststore-file: truststore.p12
    enabled-components: all
    endpoint-identification-enabled: "true"

# Custom Application Logic Configuration
app:
  runner:
    insert-count: 100
    payload-prefix: "GemFire Data Payload "
