/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import org.apache.geode.cache.Region;
import org.apache.geode.cache.client.ClientCache;
import org.apache.geode.cache.client.ClientCacheFactory;
import org.apache.geode.cache.client.ClientRegionShortcut;

import org.apache.geode.cache.client.ClientRegionFactory;


import org.json.*;

import java.util.*;



public class App {

public static void main(String[] args) throws Exception {
        System.out.println("Starting GemFire plain Java client...");

        JSONObject credentials = getGemFireCredentials();

        String locators = credentials.getString("locators");
        String username = credentials.optString("username", null);
        String password = credentials.optString("password", null);

        Properties props = new Properties();
        props.setProperty("name", "plain-java-client");
        props.setProperty("log-level", "info");

        if (username != null) {
            props.setProperty("security-username", username);
            props.setProperty("security-password", password);
        }

        ClientCacheFactory ccf = new ClientCacheFactory(props);

        for (String locator : locators.split(",")) {
            String[] parts = locator.split("\\[");
            String host = parts[0];
            int port = Integer.parseInt(parts[1].replace("]", ""));
            ccf.addPoolLocator(host, port);
        }

        ClientCache cache = ccf.create();
        System.out.println("Connected to GemFire");

        ClientRegionFactory<String, String> regionFactory =
                cache.createClientRegionFactory(ClientRegionShortcut.PROXY);

        Region<String, String> region =
                regionFactory.create("exampleRegion");

        region.put("hello", "world");
        String value = region.get("hello");

        System.out.println("Put/Get result => hello=" + value);

        // keep app alive
        Thread.currentThread().join();
    }

    private static JSONObject getGemFireCredentials() {
        String vcap = System.getenv("VCAP_SERVICES");
        if (vcap == null) {
            throw new RuntimeException("VCAP_SERVICES not found");
        }

        JSONObject root = new JSONObject(vcap);

        for (String serviceType : root.keySet()) {
            if (serviceType.toLowerCase().contains("gemfire")) {
                return root.getJSONArray(serviceType)
                           .getJSONObject(0)
                           .getJSONObject("credentials");
            }
        }

        throw new RuntimeException("GemFire service not found in VCAP_SERVICES");
    }


}
